[build]
  # Path to the root of your project (backend folder in this case)
  root = "backend"

  # Command to install dependencies without using a virtual environment
  buildCommand = "pip install --no-cache-dir -r requirements.txt"

[deploy]
  # Command to start your Flask app without using a virtual environment
  startCommand = "python app.py"
