services:
  - type: web
    name: chatbot-backend
    env: python
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
